### ISSUE TITLE
  throw new Error('Cryptr: secret must be a non-0-length string');

### ISSUE THREAD

**Issue by adadad0708** [limeforadime/liminal-shopify-order-exporter#1]
Hello
when i run :shopify node serve it show error:
F:\xam\htdocs\liminal-shopify-order-exporter-main\node_modules\cryptr\index.js:12
┃         throw new Error('Cryptr: secret must be a non-0-length string');
┃         ^
┃ 
┃ Error: Cryptr: secret must be a non-0-length string
┃     at new Cryptr (F:\xam\htdocs\liminal-shopify-order-exporter-main\node_modules\cryptr\index.js:12:15)
┃     at Object.<anonymous> (F:\xam\htdocs\liminal-shopify-order-exporter-main\server\/sessionStorage.js:10:18)
┃     at Module._compile (internal/modules/cjs/loader.js:1072:14)
┃     at Module._compile (F:\xam\htdocs\liminal-shopify-order-exporter-main\node_modules\pirates\lib\index.js:136:24)
┃     at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
┃     at Object.newLoader [as .js] (F:\xam\htdocs\liminal-shopify-order-exporter-main\node_modules\pirates\lib\index.js:141:7)
┃     at Module.load (internal/modules/cjs/loader.js:937:32)
┃     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
┃ [nodemon] app crashed - waiting for file changes before starting...

**Comment by limeforadime** [comment]
Sorry this project is still early in development
